language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tool
    - tool
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

install: false
script:
  - ./gradlew build

os:
  - linux

notifications:
  slack:
    rooms:
      - drozdzynski:uw5MXDDxTUauUjxuXPhPQW5V#general
      - drozdzynski:uw5MXDDxTUauUjxuXPhPQW5V#steppers
